version: '2'

services:
  simple-mongo:
    image: mongo
    container_name: simple-mongo
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./mongo/data/redis-data:/data
